global:
  scrape_interval: 5s

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - "localhost:9323"

  - job_name: kotlin-tomcat
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - localhost:8080

  - job_name: kotlin-coroutines
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - localhost:8081

  - job_name: kotlin-webflux
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - localhost:8082

  - job_name: java-tomcat
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - localhost:8083

  - job_name: java-webflux
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - localhost:8084